#! /bin/bash -

set -E -e -u -o pipefail || exit $?
shopt -s globstar nullglob

mkdir .public
for x in **; do
  if [[ -d "$x" ]]; then
    mkdir ".public/$x"
  else
    cp "./$x" ".public/$x"
  fi
done
mv -f .public public
